name: branch build

on:
  push:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: mipsel-buildroot-linux-musl-
            small: false
            asset: guppyscreen
            calibrate: false

          - arch: mipsel-buildroot-linux-musl-
            small: true
            asset: guppyscreen-smallscreen
            calibrate: true

          - arch: armv8-rpi3-linux-gnueabihf-
            small: false
            calibrate: false
            asset: guppyscreen-rpi

    runs-on: ubuntu-22.04
    container:
      image: pellcorp/guppydev:latest
      options: --user 1001

    env:
      CROSS_COMPILE: ${{ matrix.arch }}
      CC: ${{ matrix.arch }}
      CXX: ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set guppyscreen version
      run: |
        echo "GUPPYSCREEN_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
        run: echo "GUPPYSCREEN_VERSION=${GIT_SHA:0:7}" >> $GITHUB_ENV

    - if: matrix.small
      name: export screen size
      run: |
        echo "GUPPY_SMALL_SCREEN=${{ matrix.small }}" >> $GITHUB_ENV

    - if: matrix.calibrate
      name: export touch calibrate
      run: |
        echo "GUPPY_CALIBRATE=${{ matrix.calibrate }}" >> $GITHUB_ENV

    - name: make wpaclient
      run: make wpaclient

    - name: make libhv
      run: make libhv.a

    - name: make guppyscreen
      run: make -j

    - name: package release
      run: |
        chmod +x ./release.sh
        ./release.sh ${{ matrix.asset }} ${{ github.sha }} ${{ github.ref_name }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset }}
        path: ./${{ matrix.asset }}.tar.gz

    - name: branch release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: ${{ matrix.asset }}.tar.gz
        fail_on_unmatched_files: true
